[package]
name = "bitcoin_wallet"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.5.4"
ic-cdk-macros = "0.5.4"
candid = "0.7.14"
getrandom = { version = "0.2", features = ["custom"] }
bitcoin = "0.28.1"
serde = "1.0.132"
async-trait = "0.1.53"
k256 = { version = "0.11", default-features = false, features = ["arithmetic"] }
hmac = "0.12"
sha2 = "0.10"
ic-btc-types = { git = "https://github.com/dfinity/ic/" }

[dev-dependencies]
hex = "0.4.3"
tokio = { version = "1.17.0", features = ["full"] }