[package]
name = "bitcoin_wallet"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.5.4"
ic-cdk-macros = "0.5.4"
ic-btc-library = { git = "https://github.com/dfinity/bitcoin-library" }
getrandom = { version = "0.2", features = ["custom"] }
bitcoin = "0.28.1"
